### 线性回归简洁实现

In [1]:
import numpy as np
import torch 
from torch.utils import data
from d2l import torch as d2l

true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [2]:
def load_array(data_arrays, batch_size, is_train=True):
    '''构造一个pytorch数据迭代器'''
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels), batch_size)

next(iter(data_iter))

[tensor([[ 1.2245, -0.1733],
         [-0.7498,  0.1827],
         [-0.3464,  0.5725],
         [ 2.1708, -0.8520],
         [ 1.7708, -0.3028],
         [-1.1545,  0.1603],
         [-1.9529,  1.1591],
         [ 0.2832,  0.0903],
         [-0.0068,  0.7129],
         [ 0.3716, -0.8659]]),
 tensor([[ 7.2301],
         [ 2.0954],
         [ 1.5350],
         [11.4454],
         [ 8.7763],
         [ 1.3445],
         [-3.6686],
         [ 4.4522],
         [ 1.7673],
         [ 7.8826]])]

In [3]:
#使用框架定义的层
from torch import nn #神经网络

net = nn.Sequential(nn.Linear(2, 1)) #输入维度2， 输出维度1
# Sequential一个有序的容器，神经网络模块将按照在传入构造器的顺序依次被添加到计算图中执行 
# 同时以神经网络模块为元素的有序字典也可以作为传入参数。

In [4]:
#模型初始化
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [5]:
loss = nn.MSELoss() #L2范数/均方误差

In [6]:
#实例化SDG
trainer = torch.optim.SGD(net.parameters(), lr=0.03)
# net.parameters() 包括w和b

In [9]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step() # 调用梯度下降函数，模型更新
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

tensor([[8.1225],
        [5.3893],
        [4.6006],
        [4.6831],
        [0.3691],
        [4.7918],
        [2.3648],
        [3.6213],
        [3.6549],
        [6.8710]], grad_fn=<AddmmBackward>) tensor([[8.1254],
        [5.3711],
        [4.5963],
        [4.6881],
        [0.3633],
        [4.7835],
        [2.3399],
        [3.6386],
        [3.6676],
        [6.8740]])
tensor([[ 7.4919],
        [ 2.5034],
        [10.2152],
        [-0.5496],
        [ 1.5613],
        [ 2.6786],
        [ 8.3126],
        [-1.5169],
        [-3.0265],
        [ 2.9026]], grad_fn=<AddmmBackward>) tensor([[ 7.4908],
        [ 2.4983],
        [10.2079],
        [-0.5466],
        [ 1.5350],
        [ 2.6917],
        [ 8.3094],
        [-1.5138],
        [-3.0011],
        [ 2.8902]])
tensor([[ 7.7888],
        [ 8.5371],
        [ 6.8906],
        [-3.1200],
        [-0.7966],
        [ 9.2629],
        [ 4.7777],
        [ 9.2575],
        [ 4.8964],
        [-5.4318]], grad_fn=<AddmmB

tensor([[ 5.0356],
        [14.3996],
        [ 3.4952],
        [ 3.9575],
        [ 5.1174],
        [ 6.3937],
        [ 7.6165],
        [10.2925],
        [ 4.9718],
        [-1.2472]], grad_fn=<AddmmBackward>) tensor([[ 5.0389],
        [14.3867],
        [ 3.4916],
        [ 3.9459],
        [ 5.1272],
        [ 6.4046],
        [ 7.6252],
        [10.2896],
        [ 4.9536],
        [-1.2437]])
tensor([[ 7.5534],
        [10.6592],
        [ 6.4100],
        [ 4.5065],
        [ 2.0872],
        [ 4.4212],
        [ 8.3184],
        [ 2.2939],
        [ 0.7072],
        [-0.6011]], grad_fn=<AddmmBackward>) tensor([[ 7.5437],
        [10.6521],
        [ 6.4181],
        [ 4.5002],
        [ 2.0798],
        [ 4.4327],
        [ 8.3038],
        [ 2.2888],
        [ 0.7049],
        [-0.6076]])
tensor([[ 8.8509],
        [12.7254],
        [ 8.5272],
        [ 9.6644],
        [ 4.7019],
        [ 8.2772],
        [ 0.7115],
        [ 8.8096],
        [-4.4317],
        [ 0.213

        [1.3185]], grad_fn=<AddmmBackward>) tensor([[5.6260],
        [1.5700],
        [3.2344],
        [4.6953],
        [3.6744],
        [4.9925],
        [6.0928],
        [1.2365],
        [7.1398],
        [1.3220]])
tensor([[ 5.3917],
        [ 7.5797],
        [ 4.2423],
        [ 0.7079],
        [ 5.5669],
        [ 7.6099],
        [ 2.4548],
        [ 6.3466],
        [ 2.5420],
        [-0.4346]], grad_fn=<AddmmBackward>) tensor([[ 5.3938],
        [ 7.5769],
        [ 4.2517],
        [ 0.7049],
        [ 5.5658],
        [ 7.6019],
        [ 2.4563],
        [ 6.3582],
        [ 2.5633],
        [-0.4409]])
tensor([[ 7.9260],
        [-1.6271],
        [ 9.9667],
        [-2.1272],
        [ 1.9523],
        [ 5.1141],
        [ 8.5496],
        [ 9.9292],
        [-1.2165],
        [-2.5523]], grad_fn=<AddmmBackward>) tensor([[ 7.9342],
        [-1.6261],
        [ 9.9824],
        [-2.1327],
        [ 1.9328],
        [ 5.1109],
        [ 8.5438],
        [ 9.9403],


        [ 5.1758]], grad_fn=<AddmmBackward>) tensor([[13.8491],
        [ 1.2607],
        [ 0.6408],
        [ 6.3647],
        [ 4.9236],
        [ 2.8927],
        [ 7.4450],
        [ 5.9234],
        [ 3.4719],
        [ 5.1745]])
tensor([[ 1.0215],
        [ 9.5818],
        [ 5.2295],
        [ 9.9964],
        [ 1.6727],
        [10.9327],
        [ 6.6328],
        [ 8.0390],
        [ 3.7159],
        [ 4.0381]], grad_fn=<AddmmBackward>) tensor([[ 1.0272],
        [ 9.5610],
        [ 5.2296],
        [ 9.9958],
        [ 1.6749],
        [10.9259],
        [ 6.6290],
        [ 8.0251],
        [ 3.7084],
        [ 4.0173]])
tensor([[ 1.7480],
        [-2.2406],
        [ 5.7690],
        [-1.5170],
        [ 0.6111],
        [ 4.0067],
        [ 7.6918],
        [ 3.5733],
        [-0.0507],
        [ 1.0771]], grad_fn=<AddmmBackward>) tensor([[ 1.7313],
        [-2.2491],
        [ 5.7659],
        [-1.5138],
        [ 0.6195],
        [ 4.0185],
        [ 7.7041],
        

tensor([[ 8.4664],
        [11.4382],
        [-0.3989],
        [ 7.1112],
        [ 5.1858],
        [ 3.4253],
        [11.2169],
        [ 5.4455],
        [ 0.6593],
        [-2.5526]], grad_fn=<AddmmBackward>) tensor([[ 8.4683],
        [11.4454],
        [-0.3957],
        [ 7.1220],
        [ 5.1901],
        [ 3.4366],
        [11.2266],
        [ 5.4628],
        [ 0.6572],
        [-2.5602]])
tensor([[-5.7680],
        [ 9.0475],
        [ 0.7119],
        [ 3.3456],
        [ 2.6870],
        [ 4.9072],
        [ 8.1909],
        [-0.6958],
        [ 2.4569],
        [ 4.6870]], grad_fn=<AddmmBackward>) tensor([[-5.7635],
        [ 9.0569],
        [ 0.7169],
        [ 3.3687],
        [ 2.6779],
        [ 4.8999],
        [ 8.1811],
        [-0.6815],
        [ 2.4613],
        [ 4.7049]])
tensor([[ 3.9444],
        [ 5.5925],
        [-2.0299],
        [ 1.5870],
        [ 5.6105],
        [ 2.0875],
        [-6.2005],
        [ 9.3053],
        [11.5974],
        [ 8.982

tensor([[-1.7899],
        [-3.3316],
        [-6.5080],
        [12.7237],
        [ 2.8412],
        [ 6.8979],
        [ 2.6488],
        [-0.7207],
        [ 1.8543],
        [ 1.4669]], grad_fn=<AddmmBackward>) tensor([[-1.8066],
        [-3.3251],
        [-6.5081],
        [12.7098],
        [ 2.8505],
        [ 6.9009],
        [ 2.6637],
        [-0.7190],
        [ 1.8617],
        [ 1.4636]])
tensor([[ 8.7993],
        [12.1399],
        [ 8.5808],
        [ 1.9539],
        [ 3.8377],
        [ 2.0219],
        [ 4.7962],
        [ 3.8806],
        [ 5.4502],
        [ 6.4428]], grad_fn=<AddmmBackward>) tensor([[ 8.7873],
        [12.1371],
        [ 8.5941],
        [ 1.9328],
        [ 3.8406],
        [ 2.0251],
        [ 4.7882],
        [ 3.8833],
        [ 5.4303],
        [ 6.4453]])
tensor([[ 5.8216],
        [ 8.5402],
        [11.9275],
        [ 3.4838],
        [ 3.4659],
        [ 4.8807],
        [ 3.5746],
        [-2.5790],
        [ 6.6952],
        [ 3.572