In [2]:
### 不带参数的层

import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [4]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [5]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [9]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(4.1910e-09, grad_fn=<MeanBackward0>)

In [10]:
### 带参数的层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [14]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.8313, -0.9450, -0.2955],
        [-2.4472,  0.7534, -0.2965],
        [-0.5403,  0.8914,  0.9357],
        [-0.5061,  1.0172,  0.8184],
        [ 1.2190,  1.1600,  0.0963]], requires_grad=True)

In [15]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.8365, 2.3372],
        [0.0000, 1.6286, 1.9496]])

In [16]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[ 3.5766],
        [13.2533]])