In [2]:
import torch
from torch import nn

torch.device('cpu'), torch.device('cuda'), torch.device('cuda:1')

(device(type='cpu'), device(type='cuda'), device(type='cuda', index=1))

In [3]:
torch.cuda.device_count() # 可用GPU

0

In [4]:
def try_gpu(i=0):  #@save
    """如果存在，则返回gpu(i)，否则返回cpu()"""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():  #@save
    """返回所有可用的GPU，如果没有GPU，则返回[cpu(),]"""
    devices = [torch.device(f'cuda:{i}')
             for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cpu'), device(type='cpu'), [device(type='cpu')])

In [5]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [8]:
### 存储在GPU上
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# 假设你至少有两个GPU，下面的代码将在第二个GPU上创建一个随机张量。
Y = torch.rand(2, 3, device=try_gpu(1))
Y

tensor([[0.9208, 0.9886, 0.5322],
        [0.3827, 0.1577, 0.9900]])

In [11]:
### X 和 Y 不在同一个设备，需要复制
# Z = X.cuda(1)
# print(X)
# print(Z)

In [ ]:
# Y + Z 

In [13]:
# Z.cuda(1) is Z # True

In [14]:
### 神经网络与GPU
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())

In [15]:
net(X)

tensor([[0.3868],
        [0.3868]], grad_fn=<AddmmBackward>)

In [16]:
net[0].weight.data.device

device(type='cpu')