In [1]:
import torch

In [2]:
x = torch.arange(12)
x #张量

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
X = x.reshape((3,4))
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [18]:
X = torch.arange(12, dtype = torch.float32).reshape((3,4))
Y = torch.tensor([[1.0,2,3,4],[2,3,4,4],[7,5,6,7]])
torch.cat((X,Y), dim=0), torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 2.,  3.,  4.,  4.],
         [ 7.,  5.,  6.,  7.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  2.,  3.,  4.,  4.],
         [ 8.,  9., 10., 11.,  7.,  5.,  6.,  7.]]))

In [20]:
X==Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [21]:
X.sum()

tensor(66.)

### 形状不一样，会自我复制运算，广播机制（broadcasting mechanism）

In [22]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [24]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [26]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [28]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 运行一些操作，新结果会导致内存分配

In [33]:
before = id(Y)
Y = Y+X
id(Y) ==before

False

In [34]:
Z = torch.zeros_like(Y)
print('id(z):',id(Z))
Z[:] = X+Y
print('id(z):',id(Z))

id(z): 2033654394304
id(z): 2033654394304


In [35]:
before = id(X)
X += Y
id(X) == before

True

### Numpy

In [38]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [39]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)